name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]  # or your default branch name

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::322958063959:role/github-actions-lambda-role
          aws-region: ap-south-1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name barcelona-match-cron \
            --zip-file fileb://target/barcelona-match-cron-0.0.1-SNAPSHOT-aws.jar